### ISSUE TITLE
factory-auto is dead

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#1204]
```
Oct 18 11:29:11 packagelists check_source[29648]: [I] checking 534622
Oct 18 11:29:12 packagelists check_source[29648]: [E] 'CheckSource' object has no attribute 'repo_checker'
Oct 18 11:29:12 packagelists check_source[29648]: Traceback (most recent call last):
Oct 18 11:29:12 packagelists check_source[29648]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 646, in runner
Oct 18 11:29:12 packagelists check_source[29648]:     workfunc()
Oct 18 11:29:12 packagelists check_source[29648]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 614, in work
Oct 18 11:29:12 packagelists check_source[29648]:     self.checker.check_requests()
Oct 18 11:29:12 packagelists check_source[29648]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 144, in check_requests
Oct 18 11:29:12 packagelists check_source[29648]:     good = self.check_one_request(req)
Oct 18 11:29:12 packagelists check_source[29648]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 257, in check_one_request
Oct 18 11:29:12 packagelists check_source[29648]:     ret = func(req, a)
Oct 18 11:29:12 packagelists check_source[29648]:   File "/usr/local/bin/check_source", line 248, in check_action_delete
Oct 18 11:29:12 packagelists check_source[29648]:     if not self.skip_add_reviews and self.repo_checker is not None:
Oct 18 11:29:12 packagelists check_source[29648]: AttributeError: 'CheckSource' object has no attribute 'repo_checker'
```

**Comment by DimStar77** [comment]
Fallout of https://github.com/openSUSE/osc-plugin-factory/pull/1190

**Comment by nilxam** [comment]
@jberry-suse 

I've temporary added a workaround, http://susepaste.org/37899259

those config does not load in check_action_delete() but check_source_submission() only therefore the bot crashes in check_action_delete(), maybe you have a better solution here, so I leave it to you :)
