### ISSUE TITLE
devel-project: requests subcommand broken due to osc 0.160.0

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1205]
Another case for #1186 as the service was half functional for since `osc` was update to `0.160.0`, but just noticed.

stacktrace from `packagelists`:

```
Traceback (most recent call last):
  File "/usr/bin/osrt-devel-project", line 252, in <module>
    sys.exit(args.func(args))
  File "/usr/bin/osrt-devel-project", line 120, in requests
    exclude_target_projects=[devel_project])
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 4380, in get_request_list
    res = search(apiurl, queries=queries, request=xpath)
  File "/usr/bin/osrt-devel-project", line 41, in search
    f = http_GET(u)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3325, in http_GET
    def http_GET(*args, **kwargs):    return http_request('GET', *args, **kwargs)
  File "/usr/share/osc-plugin-factory/osclib/cache.py", line 38, in http_request
    ret = osc.core._http_request(method, url, headers, data, file)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3314, in http_request
    fd = urlopen(req, data=data)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by jberry-suse** [comment]
Specifically: openSUSE/osc@902b48fd86172e6a4fd8da966daa2e20f3e27298.
