### ISSUE TITLE
repochecker project_only post-comments doesnt work

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1259]
Nov 13 18:51:58 repochecker systemd[1]: Starting openSUSE Release Tools: repo-checker project_only for openSUSE:Leap:15.0...
Nov 13 18:51:59 repochecker osrt-repo-checker[14285]: [D] requests: 0 skipped, 0 queued
Nov 13 18:51:59 repochecker osrt-repo-checker[14285]: [I] mirroring openSUSE:Leap:15.0/standard/x86_64
Nov 13 18:52:02 repochecker osrt-repo-checker[14285]: [I] install check: start
Nov 13 18:52:14 repochecker osrt-repo-checker[14285]: [I] install check: failed
Nov 13 18:52:16 repochecker osrt-repo-checker[14285]: [I] mirroring openSUSE:Leap:15.0/standard/i586
Nov 13 18:52:19 repochecker osrt-repo-checker[14285]: [I] install check: start
Nov 13 18:52:29 repochecker osrt-repo-checker[14285]: [I] install check: failed
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]: [I] 51 package comments
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]: Traceback (most recent call last):
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/bin/osrt-repo_checker", line 497, in <module>
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     sys.exit(app.main())
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 261, in main
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     return self.cmd(args)
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 284, in cmd
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     retval = self.onecmd(argv)
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 422, in onecmd
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     return self._dispatch_cmd(handler, argv)
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/lib/python2.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     return handler(argv[0], opts, *args)
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/bin/osrt-repo_checker", line 493, in do_project_only
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     self.checker.project_only(project, opts.post_comments)
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/bin/osrt-repo_checker", line 73, in project_only
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     self.package_comments(project)
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/bin/osrt-repo_checker", line 98, in package_comments
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     project=devel_project, package=devel_package, message=message)
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:   File "/usr/share/osc-plugin-factory/ReviewBot.py", line 474, in comment_write
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]:     request = self.request
Nov 13 18:52:32 repochecker osrt-repo-checker[14285]: AttributeError: 'RepoChecker' object has no attribute 'request'

**Comment by jberry-suse** [comment]
Related to #1235 in that even if it was changed to fallback to Factory devel projects a separate comment would need to be posted to avoid flip-flopping between Leap and Factory comment.

**Comment by jberry-suse** [comment]
For SLE this may make sense to post on the packages themselves since they are the only place that makes any sense and should have bugowner set.

**Comment by jberry-suse** [comment]
For Leap, presumably it only makes sense to post to devel packages for those not taken from SLE? Or with Factory first workflow perhaps fine regardless?

**Comment by jberry-suse** [comment]
To be clear this was never intended to work as it was something left to resolve later.
