### ISSUE TITLE
factoryauto bot crashes

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#1284]
Factory auto crashes on regular delete requests (stopping all the rest from being processed):

```
Dec 03 10:14:49 packagelists systemd[1]: Started Base-validation of submit requests.
Dec 03 10:14:50 packagelists check_source[21595]: [I] checking 547602
Dec 03 10:14:50 packagelists check_source[21595]: [E] 'CheckSource' object has no attribute 'repo_checker'
Dec 03 10:14:50 packagelists check_source[21595]: Traceback (most recent call last):
Dec 03 10:14:50 packagelists check_source[21595]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 646, in runner
Dec 03 10:14:50 packagelists check_source[21595]:     workfunc()
Dec 03 10:14:50 packagelists check_source[21595]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 614, in work
Dec 03 10:14:50 packagelists check_source[21595]:     self.checker.check_requests()
Dec 03 10:14:50 packagelists check_source[21595]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 144, in check_requests
Dec 03 10:14:50 packagelists check_source[21595]:     good = self.check_one_request(req)
Dec 03 10:14:50 packagelists check_source[21595]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 257, in check_one_request
Dec 03 10:14:50 packagelists check_source[21595]:     ret = func(req, a)
Dec 03 10:14:50 packagelists check_source[21595]:   File "/usr/local/bin/check_source", line 253, in check_action_delete
Dec 03 10:14:50 packagelists check_source[21595]:     if not self.skip_add_reviews and self.repo_checker is not None:
Dec 03 10:14:50 packagelists check_source[21595]: AttributeError: 'CheckSource' object has no attribute 'repo_checker'
```

**Comment by DimStar77** [comment]
Duplicate of https://github.com/openSUSE/osc-plugin-factory/issues/1204 - which is actually not fixed in git; and @nilxam 's hotpatch was lost; readded it on the box for now
