### ISSUE TITLE
issue with staging plugin cache handling

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1326]
There seems to be a problem with the freeze command  for some users:

```
$ iosc staging -p SUSE:SLE-15:GA freeze V
SUSE:SLE-15:GA:Staging:V
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 344, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 367, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 501, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1232, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/user/.osc-plugins/osc-staging.py", line 453, in do_staging
    FreezeCommand(api).perform(prj, copy_bootstrap=opts.bootstrap)
  File "/home/user/.osc-plugins/osclib/freeze_command.py", line 146, in perform
    self.set_bootstrap_copy()
  File "/home/user/.osc-plugins/osclib/freeze_command.py", line 47, in set_bootstrap_copy
    self.api.retried_PUT(url, ET.tostring(meta))
  File "/home/user/.osc-plugins/osclib/stagingapi.py", line 174, in retried_PUT
    return self._retried_request(url, http_PUT, data)
  File "/home/user/.osc-plugins/osclib/stagingapi.py", line 154, in _retried_request
    return func(url, data=data)
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3348, in http_PUT
    def http_PUT(*args, **kwargs):    return http_request('PUT', *args, **kwargs)
  File "/home/user/.osc-plugins/osclib/cache.py", line 36, in http_request
    Cache.delete(url)
  File "/home/user/.osc-plugins/osclib/cache.py", line 206, in delete
    Cache.delete_project(apiurl, project)
  File "/home/user/.osc-plugins/osclib/cache.py", line 225, in delete_project
    shutil.rmtree(path)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/user/.cache/osc-plugin-factory/api.foo.bar/SUSE:SLE-15:GA:Staging:V'
$
 ```

**Comment by jberry-suse** [comment]
.cache/osc-plugin-factory/**api.foo.bar**/SUSE:SLE-15:GA:Staging:V

Can you provide some additional context as to the setup and how this was achieved?

**Comment by lnussel** [comment]
standard  ibs setup

**Comment by jberry-suse** [comment]
Two problems with this that require more information:

1) `shutil.rmtree()` should not care if directory is empty
```python
if os.path.exists(path):
    shutil.rmtree(path)
```
2) how is the `apiurl` set to `api.foo.bar` in a "standard ibs setup"?

**Comment by jberry-suse** [comment]
For me running with lock disabled since intial steps that seem to trigger error are all just get queries.

```
CACHE_DELETE_PROJECT https://api.suse.de SUSE:SLE-15:GA:Staging:V
```

And it works just fine. Nothing unique about freeze as the cache only sees URLs, short of a URL being present in freeze and not other commands, but this has worked fine for a year with the cache?

**Comment by jberry-suse** [comment]
My setup being

**.oscrc**
```ini
[https://api.suse.de]
user=jberry
pass=...
aliases=ibs
```

```
osc -d -A ibs staging -p SUSE:SLE-15:GA freeze V
```

**Comment by jberry-suse** [comment]
Clearly something more to this picture.

**Comment by jberry-suse** [comment]
Just to be 100% sure, since the entire point of the `rmtree()` call is to remove a non-empty directory I issued it manually for a directory with two files.

```python
shutil.rmtree('/home/jberry/.cache/osc-plugin-factory/api.opensuse.org/openSUSE:Leap:15.0:Staging')
```

Which worked as expected. After which I re-ran I received:

```
[Errno 2] No such file or directory: '/home/jberry/.cache/osc-plugin-factory/api.opensuse.org/openSUSE:Leap:15.0:Staging'
```

How one achieves the error in question is likely one of the great mysteries of the universe.

**Comment by jberry-suse** [comment]
Other [issues online seem](https://github.com/hashdist/hashdist/issues/113) to suggest nfs or similar leaving bits behind temporarily which messes up the python function, but the `api.foo.bar` still needs to be accounted for.

**Comment by jberry-suse** [comment]
@lnussel I am going to assume the output was sanitized since I see `/home/user` and as such assume that's where the `api.foo.bar` comes from. Unless further details are provided that indicate otherwise the underlying file-system issue appears to be the only real explanation.

**Comment by lnussel** [comment]
yes, hiding the details of the user :) indeed nfs could be to blame. need to check with the affected user. I couldnt reproduce myself either even though I am on nfs. Thanks!
