### ISSUE TITLE
pkglistgen: service error on commit of target scope 000product

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1440]
After deployment of #1437 now get a new problem which is seemingly unrelated, and so documenting separately.

```
Transmitting file data ....
Committed revision 158.
Waiting for server side source service run
.ERROR: we support EITHER _multibuild OR multiple spec files. Do not add both
WARNING: openSUSE-Addon-NonOss-release.changes does not exist. This package can not be submitted to openSUSE product projects.
At revision 158.
Aborting: service call failed:  /usr/lib/obs/service/source_validator --outdir /home/osrt-repo-checker/.cache/opensuse-packagelists/api.opensuse.org/openSUSE:Leap:15.0/000release-packages/tmprKywxS.source_validator.service
Traceback (most recent call last):
  File "/usr/bin/osrt-pkglistgen", line 1366, in <module>
    sys.exit(app.main())
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 261, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 284, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 422, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/cmdln.py", line 1123, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/bin/osrt-pkglistgen", line 1045, in do_update_and_solve
    self.do_update_and_solve(subcmd, copy.deepcopy(opts))
  File "/usr/bin/osrt-pkglistgen", line 1064, in do_update_and_solve
    self.update_and_solve_target(apiurl, target_project, target_config, main_repo, opts, drop_list=True)
  File "/usr/bin/osrt-pkglistgen", line 1240, in update_and_solve_target
    self.commit_package(release_dir)
  File "/usr/bin/osrt-pkglistgen", line 1361, in commit_package
    package.commit(msg='Automatic update')
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 1425, in commit
    raise oscerr.ServiceRuntimeError('A service failed with error: %d' % r)
osc.oscerr.ServiceRuntimeError
```

**Comment by coolo** [comment]
there must be a way to commit without triggering local services - osc commit has --no-service

**Comment by coolo** [comment]
skip_local_service_run=true

**Comment by lnussel** [comment]
theoretically also local_service_run=0 in .oscrc

Independent of that either we produce indeed an invalid 000release-packages or that check is wrong

**Comment by coolo** [comment]
well, let's say: that check is abused. It's supposed to check requests to Factory - and for those we indeed don't support _multibuild with multiple spec files. But 000release-packages is not a request

**Comment by lnussel** [comment]
Looking at https://github.com/openSUSE/obs-service-source_validator/commit/fa5e6e475c576e3a7fb240785816b7d337d68ada the reason for disallowing multibuild and multiple specs seem to be our tools. I guess we need to fix that

**Comment by nilxam** [comment]
I just change it in package.commit() workaround this issue.

```
- package.commit(msg='Automatic update')
+ package.commit(msg='Automatic update', skip_local_service_run=True)
```
