### ISSUE TITLE
gnome-review-bot has been damaged

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#1446]
Some recent changes caused the gnome-review-bot (used by different devel projects to have the pre-factory-auto tests) to be broken:

```
Mar 09 11:04:31 packagelists systemd[1]: Started GNOME review bot - service.
Mar 09 11:04:32 packagelists check_source[4219]: [E] sequence item 2: expected string, NoneType found
Mar 09 11:04:32 packagelists check_source[4219]: Traceback (most recent call last):
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 692, in runner
Mar 09 11:04:32 packagelists check_source[4219]:     workfunc()
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 660, in work
Mar 09 11:04:32 packagelists check_source[4219]:     self.checker.check_requests()
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 148, in check_requests
Mar 09 11:04:32 packagelists check_source[4219]:     override = self.request_override_check(req)
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 187, in request_override_check
Mar 09 11:04:32 packagelists check_source[4219]:     users = self.request_override_check_users(request.actions[0].tgt_project)
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/osclib/memoize.py", line 186, in _fn
Mar 09 11:04:32 packagelists check_source[4219]:     value = fn(*args, **kwargs)
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 172, in request_override_check_users
Mar 09 11:04:32 packagelists check_source[4219]:     users = group_members(self.apiurl, config['staging-group'])
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/osclib/memoize.py", line 186, in _fn
Mar 09 11:04:32 packagelists check_source[4219]:     value = fn(*args, **kwargs)
Mar 09 11:04:32 packagelists check_source[4219]:   File "/home/repochecker/src/osc-plugin-factory/osclib/core.py", line 25, in group_members
Mar 09 11:04:32 packagelists check_source[4219]:     url = makeurl(apiurl, ['group', group])
Mar 09 11:04:32 packagelists check_source[4219]:   File "/usr/lib/python2.7/site-packages/osc/core.py", line 3271, in makeurl
Mar 09 11:04:32 packagelists check_source[4219]:     return urlunsplit((scheme, netloc, '/'.join([path] + list(l)), query, ''))
Mar 09 11:04:32 packagelists check_source[4219]: TypeError: sequence item 2: expected string, NoneType found
```

**Comment by lnussel** [comment]
I guess you need to set the staging-group in the local config in absence of a remote one

**Comment by DimStar77** [comment]
The problem of local config is that it is project dependent - this bot has been enabled in multiple projects across OBS, not only GNOME:* (so the name is not that true anymore); but various devel projects did or want to adopt it, making it a bit less transparent (for now of course I can add config snippets for the projects I know t be using it, but that's just not scalable)

**Comment by DimStar77** [comment]
for the code it would probably save to assume that if there is no saging-group configured, nobody can control the bot by commands

**Comment by lnussel** [comment]
indeed. https://github.com/openSUSE/osc-plugin-factory/blob/master/ReviewBot.py#L172 is too hardcoded

**Comment by lnussel** [comment]
also affect maintbot

**Comment by lnussel** [comment]
hot fix deployed on packagelists. maintbot still runs off the git repo in repochecker's home
