### ISSUE TITLE
adi --move fails to work

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#680]
mlin@rana:~> osc staging adi --move wt
[(455732, {'staging': 'openSUSE:Factory:Staging:adi:22'})]
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/suse/mlin/.osc-plugins/osc-staging.py", line 400, in do_staging
    AdiCommand(api).perform(args[1:], move=opts.move, by_dp=opts.by_develproject, split=opts.split)
  File "/suse/mlin/.osc-plugins/osclib/adi_command.py", line 115, in perform
    self.create_new_adi(requests, split=split)
  File "/suse/mlin/.osc-plugins/osclib/adi_command.py", line 55, in create_new_adi
    splitter.filter_add_requests(wanted_requests)
  File "/suse/mlin/.osc-plugins/osclib/request_splitter.py", line 26, in filter_add_requests
    requests = ' ' + ' '.join(requests) + ' '
TypeError: sequence item 0: expected string, int found

**Comment by nilxam** [comment]
@jberry-suse any chance you can take a look this issue? :)
