### ISSUE TITLE
can't handle null in ignored_requests

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#708]
I ignored request without specifying a message, then the ignored_requests file listed  458967: null. Resulted in

Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/space/lnussel/git/osc/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/space/lnussel/git/osc/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/space/lnussel/git/osc/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/space/lnussel/git/osc/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/space/lnussel/git/osc/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/lnussel_factory/.osc-plugins/osc-staging.py", line 417, in do_staging
    ListCommand(api).perform(args[1:], supersede=opts.supersede)
  File "/home/lnussel_factory/.osc-plugins/osclib/list_command.py", line 37, in perform
    change_devel_requests = splitter.filter_only()
  File "/home/lnussel_factory/.osc-plugins/osclib/request_splitter.py", line 37, in filter_only
    self.suppliment(request)
  File "/home/lnussel_factory/.osc-plugins/osclib/request_splitter.py", line 84, in suppliment
    request.set('ignored', self.requests_ignored[request_id])
  File "src/lxml/lxml.etree.pyx", line 824, in lxml.etree._Element.set (src/lxml/lxml.etree.c:49602)
  File "src/lxml/apihelpers.pxi", line 570, in lxml.etree._setAttributeValue (src/lxml/lxml.etree.c:21554)
  File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src/lxml/lxml.etree.c:30197)

**Comment by jberry-suse** [comment]
Ran into same thing and already created #705.
