### ISSUE TITLE
staging adi crash

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#788]
$ osc staging -p openSUSE:Leap:42.3 adi --by-devel
	[...]
	00
	Traceback (most recent call last):
	  File "/usr/bin/osc", line 41, in <module>
	    r = babysitter.run(osccli)
	  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
	    return prg.main(argv)
	  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
	    return self.cmd(args)
	  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
	    retval = self.onecmd(argv)
	  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
	    return self._dispatch_cmd(handler, argv)
	  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
	    return handler(argv[0], opts, *args)
	  File "/home/foobar/.osc-plugins/osc-staging.py", line 501, in do_staging
	    AdiCommand(api).perform(args[1:], move=opts.move, by_dp=opts.by_develproject, split=opts.split)
	  File "/home/foobar/.osc-plugins/osclib/adi_command.py", line 118, in perform
	    self.create_new_adi((), by_dp=by_dp, split=split)
	  File "/home/foobar/.osc-plugins/osclib/adi_command.py", line 77, in create_new_adi
	    if self.api.update_superseded_request(request):
	  File "/home/foobar/.osc-plugins/osclib/stagingapi.py", line 528, in update_superseded_request
	    stage_info = self.superseded_request(request, target_pkgs)
	  File "/home/foobar/.osc-plugins/osclib/stagingapi.py", line 515, in superseded_request
	    IgnoreCommand(self).perform(request_id, message)
	  File "/home/foobar/.osc-plugins/osclib/ignore_command.py", line 21, in perform
	    for request_id in RequestFinder.find_sr(requests, self.api):
	  File "/home/foobar/.osc-plugins/osclib/request_finder.py", line 177, in find_sr
	    finder.find(pkgs, newcand)
	  File "/home/foobar/.osc-plugins/osclib/request_finder.py", line 133, in find
	    for p in pkgs:
	TypeError: 'int' object is not iterable

**Comment by lnussel** [comment]
any idea on this one?
