### ISSUE TITLE
setprio returns a json error (SLE)

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/osc-plugin-factory#908]
iosc staging setprio -p SUSE:SLE-12-SP3:GA Y important
<did some stuff>    
Traceback (most recent call last):
  File "/usr/bin/osc", line 41, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python2.7/site-packages/osc/babysitter.py", line 61, in run
    return prg.main(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 343, in main
    return self.cmd(args)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 366, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 500, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib/python2.7/site-packages/osc/cmdln.py", line 1230, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/home/fcrozat/.osc-plugins/osc-staging.py", line 580, in do_staging
    PrioCommand(api).perform(args[1:])
  File "/home/fcrozat/.osc-plugins/osclib/prio_command.py", line 63, in perform
    info = self.api.project_status(project, aggregate)
  File "/home/fcrozat/.osc-plugins/osclib/memoize.py", line 185, in _fn
    value = fn(*args, **kwargs)
  File "/home/fcrozat/.osc-plugins/osclib/stagingapi.py", line 892, in project_status
    return json.load(self.retried_GET(url))
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by nilxam** [comment]
I guess it's about infra problem affects BS right now which causes unauthorized issue, maybe give it another try later.

**Comment by jberry-suse** [comment]
`obs_factory` provides that API and the dashboard as whole was dead yesterday after deployment of recent changes. I assume the same effected IBS as it normally does. Once OBS/IBS come back will likely have the same issue unless dashboard was resolved.

**Comment by jberry-suse** [comment]
`osc -A ibs staging -p SUSE:SLE-12-SP3:GA list` worked for me.
