### ISSUE TITLE
gnome-review-bot no longer operational

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#917]
Seems the gnome-review-bot (small brother of factory-auto) is no longer functional.

It uses the same sources, just slightly different command line parameters:

> /usr/local/bin/check_source --ignore-devel --skip-add-reviews review
```
ERROR:check_source:argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 553, in runner
    workfunc()
  File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 521, in work
    self.checker.check_requests()
  File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 127, in check_requests
    good = self.check_one_request(req)
  File "/usr/local/bin/check_source", line 40, in check_one_request
    return super(CheckSource, self).check_one_request(request)
  File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 221, in check_one_request
    ret = func(req, a)
  File "/usr/local/bin/check_source", line 213, in check_action_delete
    result = osc.core.show_project_sourceinfo(self.apiurl, action.tgt_project, True, (action.tgt_package))
  File "/usr/lib/python2.7/site-packages/osc/core.py", line 3780, in show_project_sourceinfo
    query.extend(['package=%s' % quote_plus(p) for p in packages])
  File "/usr/lib64/python2.7/urllib.py", line 1303, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by DimStar77** [comment]
The bot was confused by a submission it did not understand:

https://build.opensuse.org/request/show/496407

was about deleting a repository in a project
